# Generated by Django 4.2.19 on 2025-03-09 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_departement_customuser_departement'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
