# Generated by Django 4.2.19 on 2025-03-09 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Employee', 'Employee')], default='Employee', max_length=20, null=True),
        ),
    ]
