# Generated by Django 4.2.19 on 2025-03-02 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedureflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Pending Approval', 'Pending Approval'), ('Active', 'Active'), ('Archived', 'Archived')], default='Draft', max_length=20),
        ),
        migrations.AddField(
            model_name='procedure',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
