# Generated by Django 4.2.19 on 2025-03-10 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedureflow', '0003_procedurestep'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedurestep',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Pending Approval', 'Pending Approval'), ('Done', 'Done')], default='Draft', max_length=20),
        ),
    ]
