# Generated by Django 4.2.19 on 2025-03-11 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedureflow', '0004_procedurestep_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedurestep',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
