# Generated by Django 4.2.19 on 2025-03-13 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedureflow', '0005_alter_procedurestep_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
