# Generated by Django 4.2.19 on 2025-03-13 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedureflow', '0006_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Pending Approval', 'Pending Approval'), ('Active', 'Active'), ('Executed', 'Executed')], default='Draft', max_length=20),
        ),
    ]
