# Generated by Django 4.2.19 on 2025-03-13 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procedureflow', '0007_alter_procedure_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Process',
        ),
    ]
